In [2]:
a=[1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [3]:
a.append(8)

In [4]:
print(a)

[1, 2, 3, 4, 5, 8]


In [5]:
b=[2,1,3,3,2,45,5,21]
print(b)

[2, 1, 3, 3, 2, 45, 5, 21]


In [7]:
b.sort()
print(b)


[1, 2, 2, 3, 3, 5, 21, 45]


In [8]:
b.reverse()

In [9]:
print(b)

[45, 21, 5, 3, 3, 2, 2, 1]


In [10]:
a=[1,2,3]
a.index(3)

2

In [11]:
a.index(4)

ValueError: 4 is not in list

In [12]:
a.remove(1)

In [13]:
print(a)

[2, 3]


In [14]:
a=[1,2,3]
a.pop(1)

2

In [15]:
print(a)

[1, 3]


In [16]:
dic={'name':'pay','phone':'01057862039','birth':'0224'}

In [17]:
a={1:'hi'}

In [18]:
print(dic)

{'name': 'pay', 'phone': '01057862039', 'birth': '0224'}


In [23]:
dic['phone']

'01057862039'

In [24]:
a={'a':[1,2,3]}

In [25]:
print(a)

{'a': [1, 2, 3]}


In [26]:
a={'name':'pey','phone':'01009993323','birth':'1212'}
a.keys()

dict_keys(['name', 'phone', 'birth'])

In [27]:
a.values()

dict_values(['pey', '01009993323', '1212'])

In [28]:
for i in a.keys():
    print(i)

name
phone
birth


In [29]:
for i in a.values():
    print(i)

pey
01009993323
1212


In [30]:
k_soccer={'jeonbuk':'winner','ulsan':'second',"daegu":"populist"}


In [31]:
for t in k_soccer.keys():
    print(t)

jeonbuk
ulsan
daegu


In [32]:
k_soccer.values()


dict_values(['winner', 'second', 'populist'])

In [33]:
s1=set([1,2,3])


In [46]:
hong={'국어':80,'영어':75,'수학':55}

In [52]:
sum=0
for i in hong.values():
    sum += i
print(sum)

    

    
    



210


In [53]:
def odd_1(a):
    if a%2==0:
        print("짝수입니다.")
    else:
        print("홀수입니다.")

In [55]:
odd_1(13)

홀수입니다.


In [57]:
pin="88112-1068234"

In [61]:
yyyymmdd=pin[0:5]
yyyymmdd
num=pin[6:]
num

'1068234'

In [63]:
a=[1,3,5,4,2]


In [67]:
a


[5, 4, 3, 2, 1]

In [68]:
a=0
while a < 10:
    a =a +1
    if a% 2==0:continue
    print(a)

1
3
5
7
9


In [70]:
a=0
while a<12:
    a=a+1
    if a%2==1:continue
    print(a)

2
4
6
8
10
12


In [72]:
a=0
while a <15:
    a += 1
    if a%2==1:continue
    print(a)

2
4
6
8
10
12
14


In [79]:
marks=[90,25,67,45,80]
number=0
for i in marks:
    number +=1
    if i >= 60:
        print("%d번 학생은 합격입니다." %number)
    else:
        print("%d번 학생은 불합격입니다." %number)

1번 학생은 합격입니다.
2번 학생은 불합격입니다.
3번 학생은 합격입니다.
4번 학생은 불합격입니다.
5번 학생은 합격입니다.


In [88]:
marks=[90,25,67,45,80]
number=0
for mark in marks:
    number += 1
    if mark < 60 :
        continue
    print("%d번 학생을 축하합니다. 합격입니다." %number)
    

1번 학생을 축하합니다. 합격입니다.
3번 학생을 축하합니다. 합격입니다.
5번 학생을 축하합니다. 합격입니다.


In [90]:
i =0
while True:
    i +=1
    if i>5:
        break
    print("*"*i)

*
**
***
****
*****


In [91]:
for i in range(1,101):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [92]:
A=[70,60,55,75,95,90,80,80,85,100]
total=0
for score in A:
    total += score
average= total/len(A)
print(average)

79.0


In [97]:
numbers=[1,2,3,4,5]

result=[]
for n in numbers:
    if n% 2==1:
        result.append(n*2)
print(result)

[2, 6, 10]


In [101]:
numbers=[1,2,3,4,5]
result=[n*2 for n in numbers if n%2==1]
print(result)

[2, 6, 10]


In [111]:
def add_many(*args):
    result =0
    for i in args:
        result += i
    return result
add_many(1,2,3)
    

6

In [112]:
def add_mul(choice,*args):
    if choice == 'add':
        result=0
        for i in args:
            result = result + i
    elif choice == 'mul':
        result =1
        for i in args:
            result =result *i
    return result

In [114]:
def add_mul(a,*args):
    if a=='add':
        result=0
        for i in args:
            result += i
        return result
    elif a=='mul':
        result=1
        for i in args:
            result =  result*i
        return result

In [120]:
add= lambda a, b: a+b
result= add(3,4)
print(result)

7


In [123]:
a=lambda x,y :x+y
a(10,20)


30

In [125]:
(lambda x: x+1)(3)

4

In [127]:
a=lambda x: x+3
a(5)

8

In [129]:
def my_key(string):
    return len(string.strip())

target = ['cat','tiger','dog','snake']

print(sorted(target,key=lambda x :len(x.strip())))

['cat', 'dog', 'tiger', 'snake']


In [131]:
def is_even(x):
    return x%2==0
is_even(13)


False

In [132]:
(lambda x : x%2==0)(14)


True

In [134]:
a=FourCal()

NameError: name 'FourCal' is not defined

In [135]:
class Fourcal:
    def setdata(a,b,c):
        a.b=b
        a.c=c


In [136]:
a=Fourcal()
a.setdata(4,2)

In [139]:
print(a.b)
print(a.c)

4
2


In [144]:
class Fourcal:
    def setdata(a,b,c):
        a.b=b
        a.c=c


In [150]:
c=Fourcal()
d=Fourcal()
c.setdata(4,2)
d.setdata(3,7)
id(c.b)
id(d.b)

2155153391920

In [10]:
import numpy as np
x=np.array([[1,2],[4,3]])
y=np.array([[0,1],[1,0]])
x@y

array([[2, 1],
       [3, 4]])

In [11]:
x*y

array([[0, 2],
       [4, 0]])

In [12]:
np.sin(np.pi/2)

1.0

In [17]:
np.log([1,np.e,np.e**2,0])

C:\Users\jangd\AppData\Local\Temp\ipykernel_5488\1082283890.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([1,np.e,np.e**2,0])


array([  0.,   1.,   2., -inf])

In [19]:
import numpy as np
import scipy
import linalg as la
import matplotlib.pyplot as plt


In [21]:
v=np.array([0.61,0.93,0.24,0.27])
v

array([0.61, 0.93, 0.24, 0.27])

In [23]:
v.shape

(4,)

In [25]:
v_sub=np.array([0.61,0.93,0.24,0.24])
v_sub=v[0:2]
v_sub

array([0.61, 0.93])

In [26]:
import pandas as pd


In [33]:
names="""이유덕,이재영,권종표,이재영,박민호,강상희,이재영,김지완,최승혁,이성연,박영서,박민호,전경헌,송정환,김재성,이유덕,전경헌""".split(",")

In [37]:
names[0]

'이유덕'

In [44]:
count={ x:0 for x in range(0,10) }

for x in range(1,1001):
    for i in str(x):
        count[int(i)]+=1

print(count)

{0: 192, 1: 301, 2: 300, 3: 300, 4: 300, 5: 300, 6: 300, 7: 300, 8: 300, 9: 300}


In [45]:
a={1,2,3,4}
b={3,4,5,6}
a|b

{1, 2, 3, 4, 5, 6}

In [46]:
set.union(a,b)

{1, 2, 3, 4, 5, 6}

In [47]:
a={1,2,3,4}
a.add(5)

In [48]:
a

{1, 2, 3, 4, 5}

In [49]:
a.remove(3)

In [50]:
a

{1, 2, 4, 5}

In [51]:
a.discard(2)

In [52]:
a

{1, 4, 5}

In [55]:
for i in {1,2,3,4}:
    print(i)

1
2
3
4


In [58]:
a= {i for i in 'apple'}
a

{'a', 'e', 'l', 'p'}

In [62]:
b={i for i in 'seystem'}
b

{'e', 'm', 's', 't', 'y'}

In [64]:
a= {i for i in 'pineapple' if i not in 'apl'}
a

{'e', 'i', 'n'}

In [66]:
b= {i for i in 'system' if i not in 'st'}

In [67]:
b

{'e', 'm', 'y'}